angular.module('app',[
    'ui.router',
    'ui.bootstrap',
    'menuControllers',
    'userControllers',
    'mainControllers',
    'emailControllers',
    'managementControllers',
    'itemControllers',
    'typeControllers',
    'orderControllers',
    'uiCropper',
    'bannerController',
    'galleryController',
    'galleryServices',
    'bootstrapLightbox'
]).config(function($httpProvider){
  $httpProvider.interceptors.push('AuthInterceptors');
});
